export interface BusinessIdentity {
  id: string;
  name: string;
  type: 'restaurant' | 'stay' | 'rental' | 'trip' | 'shop' | 'bar' | 'beauty' | 'service';
  primaryColor: string;
  gradientStart: string;
  gradientEnd: string;
  accentColor: string;
  logoUrl: string;
  tagline: string;
}

export const BUSINESSES: BusinessIdentity[] = [
  {
    id: 'cajori',
    name: 'Cajori Restaurant',
    type: 'restaurant',
    primaryColor: '#C1272D',
    gradientStart: '#5E0E12',
    gradientEnd: '#C1272D',
    accentColor: '#E5484D',
    logoUrl: 'https://easyryde.co.za/logos/cajori.png',
    tagline: 'Grill · Seafood · Portuguese',
  },
  {
    id: 'baobab',
    name: 'Baobab Kitchen',
    type: 'restaurant',
    primaryColor: '#B45309',
    gradientStart: '#5F2E08',
    gradientEnd: '#D97706',
    accentColor: '#F59E0B',
    logoUrl: 'https://easyryde.co.za/logos/baobab.png',
    tagline: 'Traditional · Potjie · Braai',
  },
  {
    id: 'mamas',
    name: "Mama's Pizza",
    type: 'restaurant',
    primaryColor: '#EA580C',
    gradientStart: '#6B2306',
    gradientEnd: '#F97316',
    accentColor: '#FB923C',
    logoUrl: 'https://easyryde.co.za/logos/mamas.png',
    tagline: 'Pizza · Wood-fired · Family',
  },
  {
    id: 'flame',
    name: 'Kruger Flame Grill',
    type: 'restaurant',
    primaryColor: '#0F766E',
    gradientStart: '#083B37',
    gradientEnd: '#0D9488',
    accentColor: '#14B8A6',
    logoUrl: 'https://easyryde.co.za/logos/flame.png',
    tagline: 'Steaks · Ribs · Craft',
  },
  {
    id: 'coop',
    name: 'The Coop',
    type: 'restaurant',
    primaryColor: '#CA8A04',
    gradientStart: '#6B4A05',
    gradientEnd: '#EAB308',
    accentColor: '#FACC15',
    logoUrl: 'https://easyryde.co.za/logos/coop.png',
    tagline: 'Chicken · Chips · Fast food',
  },
  {
    id: 'cu',
    name: 'CU Guesthouse',
    type: 'stay',
    primaryColor: '#0E9488',
    gradientStart: '#083B37',
    gradientEnd: '#14B8A6',
    accentColor: '#2DD4BF',
    logoUrl: 'https://easyryde.co.za/logos/cu.png',
    tagline: 'Guesthouse · Town centre',
  },
  {
    id: 'phlodge',
    name: 'Phalaborwa Lodge',
    type: 'stay',
    primaryColor: '#B45309',
    gradientStart: '#4A2A06',
    gradientEnd: '#B45309',
    accentColor: '#D97706',
    logoUrl: 'https://easyryde.co.za/logos/phlodge.png',
    tagline: 'Lodge · Bush · Safari',
  },
  {
    id: 'krugategate',
    name: 'Kruger Gate Hotel',
    type: 'stay',
    primaryColor: '#166534',
    gradientStart: '#052E16',
    gradientEnd: '#16A34A',
    accentColor: '#22C55E',
    logoUrl: 'https://easyryde.co.za/logos/krugategate.png',
    tagline: 'Hotel · Park-facing · Luxury',
  },
  {
    id: 'marula',
    name: 'Marula B&B',
    type: 'stay',
    primaryColor: '#9333EA',
    gradientStart: '#3B0764',
    gradientEnd: '#A855F7',
    accentColor: '#C084FC',
    logoUrl: 'https://easyryde.co.za/logos/marula.png',
    tagline: 'B&B · Garden · Pet-friendly',
  },
  {
    id: 'bheights',
    name: 'Baobab Heights',
    type: 'rental',
    primaryColor: '#4F46E5',
    gradientStart: '#1E1B4B',
    gradientEnd: '#6366F1',
    accentColor: '#818CF8',
    logoUrl: 'https://easyryde.co.za/logos/bheights.png',
    tagline: 'Apartments · 2-bed · Sealene Rd',
  },
  {
    id: 'mopani',
    name: 'Mopani Court',
    type: 'rental',
    primaryColor: '#0E9488',
    gradientStart: '#083B37',
    gradientEnd: '#14B8A6',
    accentColor: '#2DD4BF',
    logoUrl: 'https://easyryde.co.za/logos/mopani.png',
    tagline: 'Apartment · Bachelor · CBD',
  },
  {
    id: 'campus',
    name: 'Campus View Rooms',
    type: 'rental',
    primaryColor: '#CA8A04',
    gradientStart: '#5F3D05',
    gradientEnd: '#EAB308',
    accentColor: '#FACC15',
    logoUrl: 'https://easyryde.co.za/logos/campus.png',
    tagline: 'Student · NSFAS-friendly · Near TVET',
  },
  {
    id: 'ext4',
    name: 'Ext 4 Family Home',
    type: 'rental',
    primaryColor: '#C1272D',
    gradientStart: '#4A0D10',
    gradientEnd: '#E5484D',
    accentColor: '#F87171',
    logoUrl: 'https://easyryde.co.za/logos/ext4.png',
    tagline: 'House · 3-bed · Double garage',
  },
  {
    id: 'kruger',
    name: 'Kruger Day Safari',
    type: 'trip',
    primaryColor: '#0A7C4E',
    gradientStart: '#062A1D',
    gradientEnd: '#12A86B',
    accentColor: '#34D399',
    logoUrl: 'https://easyryde.co.za/logos/kruger.png',
    tagline: 'Big-5 · Full day · Shuttle included',
  },
  {
    id: 'canyon',
    name: 'Blyde Canyon & Hoedspruit',
    type: 'trip',
    primaryColor: '#2E6BF0',
    gradientStart: '#132B5E',
    gradientEnd: '#60A5FA',
    accentColor: '#93C5FD',
    logoUrl: 'https://easyryde.co.za/logos/canyon.png',
    tagline: 'Canyon · Waterfalls · Full day',
  },
  {
    id: 'sunset',
    name: 'Sunset Big-5 Drive',
    type: 'trip',
    primaryColor: '#C2410C',
    gradientStart: '#571B04',
    gradientEnd: '#F97316',
    accentColor: '#FB923C',
    logoUrl: 'https://easyryde.co.za/logos/sunset.png',
    tagline: 'Evening · Golden hour · Sundowner',
  },
  {
    id: 'bushbreak',
    name: 'Weekend Bush Break',
    type: 'trip',
    primaryColor: '#7C3AED',
    gradientStart: '#3B1476',
    gradientEnd: '#A78BFA',
    accentColor: '#C4B5FD',
    logoUrl: 'https://easyryde.co.za/logos/bushbreak.png',
    tagline: '2 days · Lodge · Game drives',
  },
  {
    id: 'mart',
    name: 'Makhado Mart',
    type: 'shop',
    primaryColor: '#0A7C4E',
    gradientStart: '#0B3B2A',
    gradientEnd: '#12A86B',
    accentColor: '#34D399',
    logoUrl: 'https://easyryde.co.za/logos/mart.png',
    tagline: 'Groceries & essentials',
  },
  {
    id: 'bushbar',
    name: 'The Bush Bar',
    type: 'bar',
    primaryColor: '#7C2D12',
    gradientStart: '#431407',
    gradientEnd: '#9A3412',
    accentColor: '#FB923C',
    logoUrl: 'https://easyryde.co.za/logos/bushbar.png',
    tagline: 'Live music · Happy hour',
  },
  {
    id: 'glow',
    name: 'Glow Beauty Spa',
    type: 'beauty',
    primaryColor: '#BE4B78',
    gradientStart: '#5E1D3A',
    gradientEnd: '#EC6A9F',
    accentColor: '#F9A8D4',
    logoUrl: 'https://easyryde.co.za/logos/glow.png',
    tagline: 'Spa · Treatments · Relax',
  },
  {
    id: 'cuts',
    name: 'Limpopo Cuts',
    type: 'beauty',
    primaryColor: '#1D4ED8',
    gradientStart: '#17285E',
    gradientEnd: '#3B82F6',
    accentColor: '#93C5FD',
    logoUrl: 'https://easyryde.co.za/logos/cuts.png',
    tagline: 'Barbershop · Salon',
  },
  {
    id: 'print',
    name: 'PrintWorx PHB',
    type: 'service',
    primaryColor: '#52525B',
    gradientStart: '#27272A',
    gradientEnd: '#71717A',
    accentColor: '#A1A1AA',
    logoUrl: 'https://easyryde.co.za/logos/print.png',
    tagline: 'Print · Copy · Design',
  },
  {
    id: 'fixit',
    name: 'Fix-It Plumbing',
    type: 'service',
    primaryColor: '#0E7490',
    gradientStart: '#0A3A47',
    gradientEnd: '#06B6D4',
    accentColor: '#67E8F9',
    logoUrl: 'https://easyryde.co.za/logos/fixit.png',
    tagline: 'Plumbing · Emergency · 24/7',
  },
];

const businessMap = new Map(BUSINESSES.map((b) => [b.id, b]));

export function getBusinessById(id: string): BusinessIdentity | undefined {
  return businessMap.get(id);
}

export function getBusinessesByType(type: BusinessIdentity['type']): BusinessIdentity[] {
  return BUSINESSES.filter((b) => b.type === type);
}

export function getBusinessGradient(business: BusinessIdentity): string {
  return `linear-gradient(135deg, ${business.gradientStart}, ${business.gradientEnd})`;
}
