FROM nginx:alpine

RUN apk add --no-cache openssl && \
    mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout /etc/nginx/ssl/key.pem \
      -out /etc/nginx/ssl/cert.pem \
      -subj "/C=ZA/ST=/L=/O=EasyRyde/CN=localhost" && \
    rm -f /etc/nginx/conf.d/default.conf

COPY .docker/nginx/default.conf /etc/nginx/conf.d/default.conf
